### PR TITLE
Add GitHub workflow to test the environment YAML

### PR DESCRIPTION
**Pull request by lkluft**

### CODE REVIEW

**Comment by lkluft** [comment]
Weird that is does not run the tests for the PR 🤔

**Comment by olemke** [comment]
I think an action has to exist in the master branch first, before actions in branches and PRs are executed, or?

**Comment by lkluft** [comment]
I thought that they changed that behaviour, haven't we seen that in konrad or somewhere else?

**Comment by olemke** [comment]
In arts I use a different format for the triggers:
```
on: [push, pull_request]
```

Edit: Ignore this. I just saw that it builds for the branch, just not the PR.

**Comment by olemke** [comment]
> I thought that they changed that behaviour, haven't we seen that in konrad or somewhere else?

Ah, yes, probably right.

**Comment by olemke** [comment]
Should we just merge it and see what happens?

**Review by olemke — APPROVED** [review]

**Pull request merged**
